version: '2'

services:
    php:
        build:
            context: ./php
    nginx:
        build: nginx
        ports:
            - 8000:80
        volumes:
            - ./app:/symfony-project
        volumes_from:
            - php
